# Матрицы и линейные преобразования


---



## 1. Матрица - это таблица чисел

Матрица размера m × n — это таблица из m строк и n столбцов.

In [6]:
import numpy as np
A = np.array([[1, 2, 3],
             [4, 5, 6]])
print(A)
print(A.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


В ML почти всё — матрицы. Датасет: строки — объекты, столбцы — признаки. Веса слоя: строки — выходные нейроны, столбцы — входные.


---



## 2. Транспонирование

Транспонирование меняет строки и столбцы местами:

`A.T[i, j] = A[j, i]`.

In [5]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A.T)
print(A.T.shape)

[[1 4]
 [2 5]
 [3 6]]
(3, 2)


Свойства: `(A.T).T = A, (A + B).T = A.T + B.T, (A @ B).T = B.T @ A.T` (внимание на порядок!).


---



## 3. Умножение матрицы на вектор

Это **главная операция в нейросетях.**

$$ y = A x, \quad y_i = \sum_{j} A_{ij} x_j $$

Геометрически: `A @ x` — это применение линейного преобразования `A` к точке `x`.

In [7]:
A = np.array([[2, 0], [0, 3]])
x = np.array([1, 1])

print(A @ x)

[2 3]


Поворот на угол `θ`:

In [8]:
theta = np.pi / 4 # поворачиваем на 45°
R = np.array([[np.cos(theta), -np.sin(theta)],
              [np.sin(theta), np.cos(theta)]])
print(R @ np.array([1, 0]))

[0.70710678 0.70710678]




---



## 4. Умножение матриц

$$ (AB)_{ij} = \sum_{k} A_{ik} B_{kj} $$

Размеры: `(m × n) @ (n × p) = (m × p)`. Внутренние размеры должны совпадать.

In [9]:
A = np.random.randn(3, 4)
B = np.random.randn(4, 5)
C = A @ B
print(C, '\n')
print(C.shape)

[[ 1.81597943 -1.08250487 -0.75433806  0.2262479  -2.64566307]
 [ 4.07249334 -2.30309529 -2.69822643 -0.31556065  1.72739296]
 [ 3.00164203 -2.21016912 -2.71223699  0.03094142 -0.68310423]] 

(3, 5)


Ключевая интуиция: `AB` — это композиция преобразований. Сначала применили `B`, потом `A`. Поэтому `AB ≠ BA` в общем случае.



---



## 5. Единичная и обратная матрицы

Единичная матрица `I` — единицы на диагонали, нули вне. Для любой матрицы `A·I = I·A = A`.

In [10]:
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Обратная `A^{-1}` — такая, что `A · A^{-1} = I`. Существует только для квадратных невырожденных матриц.

In [11]:
A = np.array([[1, 2], [3, 4]])
A_inv = np.linalg.inv(A)
print(A @ A_inv)

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


**В реальном коде никогда не считайте `inv(A)` для решения систем** — используйте `np.linalg.solve(A, b`). Это быстрее и численно устойчивее.



---



## 6. Линейная регрессия за 3 строки

Замечательное применение матриц. Решение методом наименьших квадратов:

$$ w = (X^T X)^{-1} X^T y $$

In [12]:
X = np.random.randn(100, 5)
true_w = np.array([1, -2, 3, 0.5, -1])
y = X @ true_w + 0.1 * np.random.randn(100)

w_hat = np.linalg.solve(X.T @ X, X.T @ y)
print(w_hat)

[ 1.00054124 -2.00249939  2.99797348  0.4872462  -1.0038237 ]


Это уже работающая линейная регрессия. Без `sklearn`. На чистом `NumPy`. Запомните этот момент.


---



## 7. Ранг и вырожденность

**Ранг матрицы** — число линейно независимых строк (или столбцов). Если ранг меньше размера — матрица вырождена, обратной нет.

In [13]:
A = np.array([[1, 2], [2, 4]])
print(np.linalg.matrix_rank(A))

1


Где это в ML: если в датасете два признака линейно зависят друг от друга (например, температура в Цельсиях и в Фаренгейтах), матрица X^T X становится вырожденной и линейная регрессия ломается. Это решается регуляризацией (Ridge добавляет λI).


---

