# Векторы и операции над ними



> Любые данные в ML -> **векторы**, без понимания операций над ними, не получиться понять что происходит внутри любой модели.

---





## 1. Что такое вектор

В ML **вектором** называется упорядоченный набор данных. Вот и всё.

In [15]:
x = [11.0, 9.0, 20.0, 0.5]

**Размерность вектора**  — количество чисел в нем.

In [16]:
import numpy as np
x = np.array([11.0, 9.0, 20.0, 0.5])
print(x.shape)
print(x.ndim)

(4,)
1


In [17]:
print(x)

[11.   9.  20.   0.5]




---



## 2. Сложение и умножение на скаляр

**Сложение векторов**  — поэлементно. Размерности должны совпадать.

$$ a + b = (a_1 + b_1, a_2 + b_2, \dots, a_n + b_n) $$

**Умножение векторов**  — каждый элемент умножается на число.

$$ \alpha \cdot a = (\alpha a_1, \alpha a_2, \dots, \alpha a_n) $$

In [18]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(3 * a)
print(a - 2.5 * b)

[5 7 9]
[3 6 9]
[ -9.  -10.5 -12. ]




---



## 3. Скалярное произведение (по-крутому dot product)

Без преувеличения, **самая важная операция** в ML.

$$ a \cdot b = \sum_{i=1}^{n} a_i b_i = a_1 b_1 + a_2 b_2 + \dots + a_n b_n $$

Результатом будет одно число, то есть скаляр.

In [19]:
a = np.array([0, 9, 1, 1])
b = np.array([2, 0, 0, 5])

# Три эквивалентных способа
print(np.dot(a, b))
print(a @ b)
print((a * b).sum())

5
5
5




---



## 4. Норма вектора (по-простому длина)

**Евклидова норма (L2)**  — длина вектора.

$$ \|a\|_2 = \sqrt{a_1^2 + a_2^2 + \dots + a_n^2} = \sqrt{a \cdot a} $$

In [20]:
a = np.array([0.1, 23.0])

print(np.linalg.norm(a))
# или
print(np.sqrt(a @ a))

23.000217390276987
23.000217390276987


**L1 норма**  — сумма модулей.

$$ \|a\|_1 = |a_1| + |a_2| + \dots + |a_n| $$

In [21]:
print(np.linalg.norm(a, ord=1))

23.1



> L1 даёт разреженные решения (Lasso), L2  — гладкие (Ridge). Это будет понятно в регуляризации.





---



## 5. Косинус угла между векторами

Самая частая метрика похожести похожести в ML.

$$ \cos(\theta) = \frac{a \cdot b}{\|a\| \cdot \|b\|} $$



> Значения от -1 до 1. Близко к 1 означает, что векторы направлены в одну сторону, 0  — перпендикулярны, -1  — противоположны.



In [22]:
def cosine(a, b):
    return (a @ b) / (np.linalg.norm(a) * np.linalg.norm(b))

a = np.array([1, 0])
b = np.array([1, 1])
print(cosine(a, b))

0.7071067811865475


Где это в ML: поиск похожих документов, рекомендации, семантический поиск, эмбеддингов.